name: Publish Github Pages

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: '0.120.4'
            extended: true
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: hugo --minify
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
